/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0
 *
 * Project: 'LowPowerSensorSampling.debug+E7-HP' 
 * Target:  'debug+E7-HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* AlifSemiconductor::CMSIS Driver:SPI@2.1.0 */
#define RTE_Drivers_SPI              /* Driver SPI */
/* AlifSemiconductor::CMSIS Driver:USART@2.1.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:DMA@2.1.0 */
#define RTE_Drivers_DMA                   /* Driver DMA*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.1.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:LPTIMER@2.1.0 */
#define RTE_Drivers_LPTIMER              /* Driver LPTIMER */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.1.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
